### ISSUE TITLE
Creating a project using `bud` command doesnt work as in read me

### ISSUE THREAD

**Issue by Aditiayunda** [livebud/bud#199] opened 2022-07-09 05:48 UTC
when i do `bud create hello` it gives error
```
❯ bud create hello
| create: Unable to infer a module name. Try again using the module <path> name.create hello                                                                                                                                                   ✔  at 01:47:58 PM  ▓▒░

For example,
        bud create --module=github.com/my/app hello
```

when i followed the instruction to add module and create the project, it cant be started, it gives this error 
```
| Listening on http://127.0.0.1:3000                                                                                                                                                              
| conjure: generate “bud/internal/app/main.go”. app: unable to load state: app: unable to wire. di: unable to wire “github.com/xxxx/hello/bud/program”.loadWeb function. di: unable to find definition for param “github.com/livebud/bud/package/router”.*Router in “github.com/xxxx/hello/bud/internal/app/web”.*Server . parser: unable to find declaration for “github.com/livebud/bud/package/router”.Router in “bud/internal/app/web/web.go”. stat /Users/xxxx/sdk/go1.18:/Users/xxxx/go/pkg/mod/github.com/livebud/bud@v0.2.1: no such file or directory
```

**Comment by 012e** [comment] 2022-07-09 06:09
Hey @Aditiayunda, are you using GOPATH with multiple directories? Looks like a duplicate of #78

**Comment by Aditiayunda** [comment] 2022-07-09 06:15
it seems like it @012e, thanks for the help. i will try to resolve and run this again

**Closed** 2022-07-09 06:15 UTC
