### ISSUE TITLE
stat $TMPDIR/bud/cache/4Lh3YtPjLfk: not a directory

### ISSUE THREAD

**Issue by alecthomas** [livebud/bud#27] opened 2022-05-14 01:42 UTC
Thanks!

**Comment by codenoid** [comment] 2022-05-14 03:43
You could temporary use [tj/gobinaries](https://github.com/tj/gobinaries)
```sh
curl -sf https://gobinaries.com/livebud/bud | sh
```

**Comment by alecthomas** [comment] 2022-05-14 03:50
The darwin/amd64 binaries work okay through Rosetta for now.

**Comment by alecthomas** [comment] 2022-05-14 03:50
tj/gobinaries is pretty cool though!

**Comment by alecthomas** [comment] 2022-05-14 03:53
Although it fails to work for me:

```
$ curl -sf https://gobinaries.com/livebud/bud | sh

  ==> Downloading github.com/livebud/bud@master
  ==> Resolved version master to v0.0.9
  ==> Downloading binary for darwin arm64

  Error downloading, got 500 response from server
```

**Comment by matthewmueller** [comment] 2022-05-14 06:15
Hey @alecthomas, thanks for stopping by! I'm a fan of your work. 

I've been told it works through Rosetta emulation:

> I was able to get Bud running under Rosetta 2 by starting a Rosetta2 shell: arch -arch x86_64 zsh. I have this aliased to rosetta because I need it every once in a while.

But I'll add native support for darwin/arm64 this weekend. Closing as a duplicate of #6

**Comment by alecthomas** [comment] 2022-05-14 06:21
🙏

**Comment by matthewmueller** [comment] 2022-05-14 09:22
Please try again:

```sh
curl -sf curl https://raw.githubusercontent.com/livebud/bud/main/install.sh | sh
```

Wasn't able to test this since I'm not on an M1. I did see some V8 warnings, so let's see 😅

**Comment by alecthomas** [comment] 2022-05-14 09:38
Nice, thanks!

It does run, but it fails to serve or build with:

```
🐚 ~/…/hello/hello $ bud run         
| Listening on http://0.0.0.0:3000
| stat /var/folders/33/k1v9knb976dfb6s0f94qxn080000gn/T/bud/cache/4Lh3YtPjLfk: not a directory
```

**Comment by matthewmueller** [comment] 2022-05-14 10:48
Ah interesting, that shouldn't be a directory, it's actually a cached binary. Looking into it!

**Comment by alecthomas** [comment] 2022-05-14 11:12
```
🐚 ~/Projects/hello $ cat /var/folders/33/k1v9knb976dfb6s0f94qxn080000gn/T/bud
Internal Server Error
```

**Comment by alecthomas** [comment] 2022-05-14 11:13
Deleting that file fixed it, but I have no idea how it got there 🤔

**Comment by matthewmueller** [comment] 2022-05-14 11:41
I'll look into this after dinner 😄

**Comment by kevwan** [comment] 2022-05-14 12:31
Got the same issue.

**Comment by matthewmueller** [comment] 2022-05-14 18:38
Looked into it but haven't been able to repro it. A couple questions:

1. Were the repro steps the following? 

```
curl -sf curl https://raw.githubusercontent.com/livebud/bud/main/install.sh | sh
bud create hello
cd hello
bud run
```

2. Were you able to reliably reproduce the error multiple times?

3. @kevwan are you on an M1 as well?

The problem appears to be somewhere in https://github.com/livebud/bud/blob/main/internal/buildcache/buildcache.go.

What's odd is the "not a directory" error only seems to appear with `os.ReadDir`: https://github.com/golang/go/blob/2580d0e08d5e9f979b943758d3c49877fb2324cb/src/cmd/go/internal/fsys/fsys.go. This makes me think there's a ReadDir happening under the hood somewhere.

I'd dig more into this tomorrow!

**Comment by alecthomas** [comment] 2022-05-14 21:55
I suspect the error occurs with Open() when an [intermediate path element is a file](https://go.dev/play/p/6hnVlCX0APz). eg. `os.Open("/etc/passwd/foo")`

**Comment by kevwan** [comment] 2022-05-15 03:11
> Looked into it but haven't been able to repro it. A couple questions:
> 
> 1. Were the repro steps the following?
>    ```
>    curl -sf curl https://raw.githubusercontent.com/livebud/bud/main/install.sh | sh
>    bud create hello
>    cd hello
>    bud run
>    ```
> 2. Were you able to reliably reproduce the error multiple times?
> 3. @kevwan are you on an M1 as well?
> 
> The problem appears to be somewhere in https://github.com/livebud/bud/blob/main/internal/buildcache/buildcache.go.
> 
> What's odd is the "not a directory" error only seems to occur within an `os.ReadDir`: https://github.com/golang/go/blob/2580d0e08d5e9f979b943758d3c49877fb2324cb/src/cmd/go/internal/fsys/fsys.go. This makes me think there's a ReadDir happening under the hood somewhere.

Yes, latest M1.

**Comment by matthewmueller** [comment] 2022-05-15 07:42
Thanks @kevwan, I think I'm unable to repro it because either it works on darwin/amd64 or because I'm still on OSX Catalina (v10.15).

After thinking about this some more, I think I'm just going to move the cache and tmp directories into your project's `bud` build directory. I was tempted to do this before to keep everything self-contained, but wasn't sure if I wanted to clutter up the bud directory. That would fix this issue and also #30.

**Comment by kevwan** [comment] 2022-05-15 08:01
> Thanks @kevwan, I think I'm unable to repro it because either it works on darwin/amd64 or because I'm still on OSX Catalina (v10.15).
> 
> I'm tempted to move the cache and tmp directories into your project's `bud` build directory Most people will `.gitignore` that directory anyways. I was thinking of doing this earlier to keep everything self-contained, but wasn't sure if it was worth cluttering up the bud directory. These problems seem to make this solution more enticing. That should fix this issue and also #30.
> 
> What do you think?

I think self-contained is great. I think both clear architecture and better user experience are important.

If we can ship the project with the usage stable for further changes, I'd like to provide better user experience. And we improve the design later. My point is compatibility concern.

**Comment by matthewmueller** [comment] 2022-05-15 17:19
Would you mind pulling down the branch in the following PR and testing if this fixes your problem? https://github.com/livebud/bud/pull/50

**Closed** 2022-05-16 06:38 UTC

**Comment by kevwan** [comment] 2022-05-16 13:02
I'm still getting this error.

<img width="678" alt="image" src="https://user-images.githubusercontent.com/1918356/168598548-5648315b-5d06-4974-bf9a-052d687ce310.png">

**Comment by matthewmueller** [comment] 2022-05-16 13:08
Ah, it looks like you're not on latest. I'm going to create a new release now, hang tight.

**Comment by matthewmueller** [comment] 2022-05-16 13:16
@kevwan can you try again on [v0.1.3](https://github.com/livebud/bud/releases/tag/v0.1.3)

```
curl -sf https://raw.githubusercontent.com/livebud/bud/main/install.sh | sh
```

**Comment by kevwan** [comment] 2022-05-16 13:22
Great! It's working now. Thanks!

I guess you updated v0.1.2, but it's cached by CDN.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/1918356/168602235-fef1a643-481a-4b66-82ee-cb1c23e261c9.png">
