### ISSUE TITLE
../../../go/pkg/mod/github.com/livebud/bud@v0.1.4/package/scaffold/template.go:28:8: undefined: any

### ISSUE THREAD

**Issue by forging2012** [livebud/bud#90] opened 2022-05-27 04:03 UTC
```
➜  bud-hello bud version
     bud: 0.1.4
  svelte: 3.47.0
   react: 18.0.0
➜  bud-hello bud run
| Listening on http://127.0.0.1:3000
# github.com/livebud/bud/package/scaffold
../../../go/pkg/mod/github.com/livebud/bud@v0.1.4/package/scaffold/template.go:28:8: undefined: any
note: module requires Go 1.18
➜  bud-hello go version
go version go1.17.10 darwin/amd64
```

**Comment by matthewmueller** [comment] 2022-05-27 06:12
Oh wow, looks like an `any` snuck in there, thanks! I'll setup CI to catch this.

**Comment by forging2012** [comment] 2022-05-27 16:43
```
➜  bud-hello bud version
     bud: 0.1.4
  svelte: 3.47.0
   react: 18.0.0
➜  bud-hello go version
go version go1.18.2 darwin/amd64
➜  bud-hello bud run
| Listening on http://127.0.0.1:3000
build flag -mod=mod only valid when using modules
| exit status 1
```

**Comment by forging2012** [comment] 2022-05-27 16:56
```
➜  bud-new go env -w GO111MODULE=on
➜  bud-new bud run
| Listening on http://127.0.0.1:3000
```
It works~!

**Comment by matthewmueller** [comment] 2022-05-28 05:15
@forging2012 glad to hear you got it working. I'm surprised `GO111MODULE=on` was not the default for `Go 1.18`. Are you explicitly overriding that in your dotfiles or something?

**Comment by forging2012** [comment] 2022-05-29 16:05
```
I update golang version to go1.18.2.
Error follow:

➜  bud-hello bud version
     bud: 0.1.4
  svelte: 3.47.0
   react: 18.0.0
➜  bud-hello go version
go version go1.18.2 darwin/amd64
➜  bud-hello bud run
| Listening on http://127.0.0.1:3000
build flag -mod=mod only valid when using modules
| exit status 1
```

When I run:
go env -w GO111MODULE=on
bud run
| Listening on http://127.0.0.1:3000
It works for me ~!

**Comment by matthewmueller** [comment] 2022-05-30 06:58
Hmm, I'm not able to reproduce the `GO111MODULE=on` requirement. A couple questions:

1. What do you get when you run `go env GO111MODULE`?
2. What does `ls hello-bud` show?

**Comment by forging2012** [comment] 2022-05-30 10:39
```
1、➜  bud-hello go env GO111MODULE
on
2、
➜  bud-hello ls -al
total 56
drwx------   9 admin  staff   288 May 27 12:01 .
drwxr-xr-x  17 admin  staff   544 May 28 00:54 ..
-rw-r--r--   1 admin  staff    19 May 27 12:00 .gitignore
drwxr-xr-x   8 admin  staff   256 May 30 18:34 bud
-rw-r--r--   1 admin  staff   908 May 27 12:01 go.mod
-rw-r--r--   1 admin  staff  9521 May 27 12:01 go.sum
drwxr-xr-x  10 admin  staff   320 May 27 12:01 node_modules
-rw-r--r--   1 admin  staff  2256 May 27 12:01 package-lock.json
-rw-r--r--   1 admin  staff   117 May 27 12:01 package.json
```

```
➜  bud-hello go version
go version go1.18.2 darwin/amd64
➜  bud-hello bud version
     bud: 0.1.4
  svelte: 3.47.0
   react: 18.0.0
➜  bud-hello bud run
| Listening on http://127.0.0.1:3000
```

**Comment by matthewmueller** [comment] 2022-06-01 00:45
Okay cool, and I'm tracking `undefined: any` elsewhere. We'll confirm the fix in https://github.com/livebud/bud/pull/95, so I'm going to close this one.

**Closed by matthewmueller** 2022-06-01 00:45 UTC
